# fly.toml app configuration file generated for t5-chat on 2025-06-08T11:38:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 't5-chat'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
